baseurl = "https://tanehaines.com/"
languageCode = "en-us"
theme = "terminal"
pagination.pagerSize = 5

[markup.highlight]
  noClasses = false

[params]
  contentTypeName = "posts"
  showMenuItems = 5
  showLanguageSelector = false
  fullWidthTheme = false
  centerTheme = true  # Updated to center the theme
  autoCover = true
  showLastUpdated = false
  
  # RSS Feed Configuration
  rssLimit = 20  # Limit number of items in RSS feed
  rssFullContent = true  # Include full content in RSS feed

  [languages.en]
    languageName = "English"
    title = "Tane H. Blog"

    [languages.en.params]
      subtitle = ""
      owner = "Tane"
      keywords = ""
      copyright = ""
      menuMore = "Show more"
      readMore = "Read more"
      readOtherPosts = "Read other posts"
      newerPosts = "Newer posts"
      olderPosts = "Older posts"
      missingContentMessage = "Page not found..."
      missingBackButtonLabel = "Back to home page"
      minuteReadingTime = "min read"
      words = "words"

      [languages.en.params.logo]
        logoText = "Tane Haines"
        logoHomeLink = "/"

    # Define main navigation menu
    [languages.en.menu]
      [[languages.en.menu.main]]
        identifier = "about"
        name = "About Me"
        url = "/about"  

      [[languages.en.menu.main]]
        identifier = "blog-posts"
        name = "Blog Post"
        url = "/posts" 

[caches]
  [caches.images]
    dir = ':cacheDir/images'

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      hardWraps = true

# RSS Feed Configuration
[outputs]
  home = ["HTML", "RSS"]
  page = ["HTML"]
  section = ["HTML", "RSS"]
  taxonomy = ["HTML", "RSS"]
