baseurl = "http://tanehaines.com/"
languageCode = "en-us"
theme = "terminal"
pagination.pagerSize = 5

[markup.highlight]
  noClasses = false

[params]
  contentTypeName = "posts"
  showMenuItems = 5
  showLanguageSelector = false
  fullWidthTheme = false
  centerTheme = true  # Updated to center the theme
  autoCover = true
  showLastUpdated = false

  [languages.en]
    languageName = "English"
    title = "Tane H. Blog"

    [languages.en.params]
      subtitle = ""
      owner = "Tane"
      keywords = ""
      copyright = ""
      menuMore = "Show more"
      readMore = "Read more"
      readOtherPosts = "Read other posts"
      newerPosts = "Newer posts"
      olderPosts = "Older posts"
      missingContentMessage = "Page not found..."
      missingBackButtonLabel = "Back to home page"
      minuteReadingTime = "min read"
      words = "words"

      [languages.en.params.logo]
        logoText = "Tane Haines"
        logoHomeLink = "/"

    # Define main navigation menu
    [languages.en.menu]
      [[languages.en.menu.main]]
        identifier = "about"
        name = "About Me"
        url = "/about"  

      [[languages.en.menu.main]]
        identifier = "blog-posts"
        name = "Blog Post"
        url = "/posts" 

      [[languages.en.menu.main]]
        identifier = "cv"
        name = "Short CV"
        url = "/cv"  

      [[languages.en.menu.main]]
        identifier = "showcase"
        name = "Showcase"
        url = "/showcase"  

      [[languages.en.menu.main]]
        identifier = "writeups"
        name = "Writeups"
        url = "/writeups" 
[permalinks]
  posts = "/posts/:slug/"
[caches]
  [caches.images]
    dir = ':cacheDir/images'